### ISSUE TITLE
`.toJSON` method not showing up in LSP

### ISSUE THREAD

**Issue by brandonpittman** [biggyspender/ts-iterable-functions#18]
I created a range using the `range` function. If I log the result, I see there's a `.toJSON()` method available, but the types aren't showing up in my editor.

<img width="510" alt="CleanShot 2022-06-02 at 13 09 56@2x" src="https://user-images.githubusercontent.com/967145/171551426-1f0d359c-09d8-4bc6-a888-05cb468c95af.png">

**Comment by biggyspender** [comment]
@brandonpittman The inclusion of a (non-advertised) `toJSON` method is only to [allow `JSON.stringify` to operate](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior) over returned iterables so that they behave like array from the POV of the serializer. I'm on the fence as to whether this should form part of the contract... TBH it's only really there to help with debugging.

The expected way of materializing the iterable in user-code would be a spread, the `_toArray` function, or `Array.from`

`[...range(5,5)]`

`_toArray(range(5,5))`

`Array.from(range(5,5))`

**Comment by brandonpittman** [comment]
> @brandonpittman The inclusion of a (non-advertised) `toJSON` method is only to [allow `JSON.stringify` to operate](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior) over returned iterables so that they behave like array from the POV of the serializer. I'm on the fence as to whether this should form part of the contract... TBH it's only really there to help with debugging.
> 
> The expected way of materializing the iterable in user-code would be a spread, the `_toArray` function, or `Array.from`
> 
> `[...range(5,5)]`
> 
> `_toArray(range(5,5))`
> 
> `Array.from(range(5,5))`

Makes sense. the use of `toArray` kinda snuck past me and how often you should reach for the `_` version of functions was clear at first either. Thanks for following up on this.

**Comment by biggyspender** [comment]
@brandonpittman The library is primarily designed to work with `pipe` functions. The underscore prefixed functions exist where invoking a pipe would be unnecessarily verbose... for instance:

```
pipeInto(
   range(5, 5),
   toArray()
)
```

vs

```
_toArray(range(5, 5))
```

HTH

**Comment by brandonpittman** [comment]
@biggyspender Thanks for the clarification! I'm using this library at work and I'm enjoying digging into all it can do.
